name: BDI Main Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main-pipeline:
    name: Main BDI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: 1. Run Code Guardian Scan
        run: python github_actions_quantum/check_secrets.py

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      - name: 2. Run Other Agents
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python github_actions_quantum/quantum/business_analyzer.py
          python github_actions_quantum/quantum/evolution_chamber.py
          python github_actions_quantum/resource_auditor.py

      - name: Report Final Status to Vercel
        if: always()
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          curl -s -X POST "$VERCEL_URL/api/status" \
          -H "Content-Type: application/json" \
          -d '{"component": "main-pipeline", "status": "${{ job.status }}"}'
