name: Quantum BDI Processing & Security Guard

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  security-scan:
    name: Code Guardian Security Scan
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python github_actions_quantum/check_secrets.py
      - name: Report Status to Vercel
        if: always()
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          curl -X POST "$VERCEL_URL/api/status" -H "Content-Type: application/json" -d '{"component": "code_guardian", "status": "${{ job.status }}"}'

  # SEMUA JOB LAIN (run-quantum-pipeline, business-analysis, evolution-chamber)
  # Kita akan NONAKTIFKAN SEMENTARA untuk fokus pada ResourceOptimizer
  # Cukup beri tanda '#' di depan nama job-nya

  self-healing-patrol:
    name: Self-Healing Patrol
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - run: pip install requests
      - name: Run SelfHealingAgent Patrol
        env: { VERCEL_URL: ${{ secrets.VERCEL_URL }} }
        run: python github_actions_quantum/quantum/healing_protocol.py
      - name: Report Status to Vercel
        if: always()
        env: { VERCEL_URL: ${{ secrets.VERCEL_URL }} }
        run: |
          curl -X POST "$VERCEL_URL/api/status" -H "Content-Type: application/json" -d '{"component": "self_healing", "status": "${{ job.status }}"}'
          
  resource-optimizer:
    name: Resource Optimizer Audit
    if: always() # Kita paksa jalan untuk testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - run: pip install requests
      - name: Run ResourceOptimizerAgent Audit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python github_actions_quantum/resource_auditor.py
